- name: nginx with handler
  hosts: server
  become: yes
  tasks:
  - name: Install nginx
    package:
      name: nginx
      state: present
    notify:
      Start nginx
  handlers:
  - name: Start nginx
    service:
      name: nginx
      state: started
